name: Create a tag

on:
  push:
    branches:
      - master
      - release-workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Maybe create a tag
        run: bash bin/release.sh

      - name: Install Dependencies
        run: composer install

      - name: Build the release
        run: vendor/bin/wp dist-archive . astra-notices.zip
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.BRAINSTORM_FORCE_RELEASE }}
          body: ''
          files: astra-notices.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
